# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../panneau_de_controle.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.direct_pH = QtWidgets.QLCDNumber(self.centralwidget)
        self.direct_pH.setGeometry(QtCore.QRect(530, 60, 91, 51))
        self.direct_pH.setObjectName("direct_pH")
        self.electrode_is_stable = QtWidgets.QProgressBar(self.centralwidget)
        self.electrode_is_stable.setGeometry(QtCore.QRect(650, 90, 81, 21))
        self.electrode_is_stable.setMaximum(4)
        self.electrode_is_stable.setProperty("value", 2)
        self.electrode_is_stable.setTextVisible(False)
        self.electrode_is_stable.setObjectName("electrode_is_stable")
        self.Abs_direct = QtWidgets.QGraphicsView(self.centralwidget)
        self.Abs_direct.setGeometry(QtCore.QRect(10, 50, 501, 331))
        self.Abs_direct.setObjectName("Abs_direct")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(530, 30, 71, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 421, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(650, 50, 71, 41))
        self.label_3.setObjectName("label_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 430, 121, 51))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 390, 191, 41))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 500, 81, 31))
        self.label_5.setObjectName("label_5")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(30, 540, 121, 51))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(190, 550, 271, 41))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(190, 440, 281, 41))
        self.checkBox_2.setObjectName("checkBox_2")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(530, 160, 211, 221))
        self.tableView.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableView.setObjectName("tableView")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(530, 115, 211, 41))
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(530, 530, 211, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(530, 430, 211, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        self.menuPanneau_de_contr_le = QtWidgets.QMenu(self.menubar)
        self.menuPanneau_de_contr_le.setObjectName("menuPanneau_de_contr_le")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuPanneau_de_contr_le.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.electrode_is_stable.setFormat(_translate("MainWindow", "%p%"))
        self.label.setText(_translate("MainWindow", "pH"))
        self.label_2.setText(_translate("MainWindow", "Absorbance direct et référence"))
        self.label_3.setText(_translate("MainWindow", "électrode stable"))
        self.label_4.setText(_translate("MainWindow", "integration time (ms)"))
        self.label_5.setText(_translate("MainWindow", "average"))
        self.checkBox.setText(_translate("MainWindow", "non linearity correction"))
        self.checkBox_2.setText(_translate("MainWindow", "electric dark correction"))
        self.label_6.setText(_translate("MainWindow", "dernière calibration"))
        self.pushButton.setText(_translate("MainWindow", "lancement du titrage"))
        self.pushButton_2.setText(_translate("MainWindow", "calibration"))
        self.menuPanneau_de_contr_le.setTitle(_translate("MainWindow", "Panneau de contrôle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
