# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../spectro_param.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1799, 954)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(1690, 850, 81, 71))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.darkSpectrum = QtWidgets.QGraphicsView(Dialog)
        self.darkSpectrum.setGeometry(QtCore.QRect(960, 20, 521, 291))
        self.darkSpectrum.setObjectName("darkSpectrum")
        self.abs_courante = QtWidgets.QGraphicsView(Dialog)
        self.abs_courante.setGeometry(QtCore.QRect(10, 50, 941, 621))
        self.abs_courante.setObjectName("abs_courante")
        self.label_dark = QtWidgets.QLabel(Dialog)
        self.label_dark.setGeometry(QtCore.QRect(1560, 130, 191, 31))
        self.label_dark.setObjectName("label_dark")
        self.reference = QtWidgets.QGraphicsView(Dialog)
        self.reference.setGeometry(QtCore.QRect(960, 320, 521, 311))
        self.reference.setObjectName("reference")
        self.label_ref = QtWidgets.QLabel(Dialog)
        self.label_ref.setGeometry(QtCore.QRect(1560, 440, 91, 31))
        self.label_ref.setObjectName("label_ref")
        self.intensity = QtWidgets.QGraphicsView(Dialog)
        self.intensity.setGeometry(QtCore.QRect(960, 640, 521, 291))
        self.intensity.setObjectName("intensity")
        self.label_intensity = QtWidgets.QLabel(Dialog)
        self.label_intensity.setGeometry(QtCore.QRect(1560, 760, 101, 31))
        self.label_intensity.setObjectName("label_intensity")
        self.label_abs = QtWidgets.QLabel(Dialog)
        self.label_abs.setGeometry(QtCore.QRect(20, 10, 91, 31))
        self.label_abs.setObjectName("label_abs")
        self.refresh_dark_spectrum = QtWidgets.QPushButton(Dialog)
        self.refresh_dark_spectrum.setGeometry(QtCore.QRect(1560, 180, 81, 31))
        self.refresh_dark_spectrum.setObjectName("refresh_dark_spectrum")
        self.refresh_ref = QtWidgets.QPushButton(Dialog)
        self.refresh_ref.setGeometry(QtCore.QRect(1560, 490, 81, 31))
        self.refresh_ref.setObjectName("refresh_ref")
        self.Tint = QtWidgets.QSpinBox(Dialog)
        self.Tint.setGeometry(QtCore.QRect(30, 710, 71, 31))
        self.Tint.setMinimum(1)
        self.Tint.setMaximum(1000)
        self.Tint.setProperty("value", 10)
        self.Tint.setObjectName("Tint")
        self.label_tint = QtWidgets.QLabel(Dialog)
        self.label_tint.setGeometry(QtCore.QRect(30, 680, 71, 21))
        self.label_tint.setObjectName("label_tint")
        self.label_avg = QtWidgets.QLabel(Dialog)
        self.label_avg.setGeometry(QtCore.QRect(180, 680, 81, 21))
        self.label_avg.setObjectName("label_avg")
        self.avg = QtWidgets.QSpinBox(Dialog)
        self.avg.setGeometry(QtCore.QRect(180, 710, 71, 31))
        self.avg.setMinimum(1)
        self.avg.setMaximum(500)
        self.avg.setProperty("value", 1)
        self.avg.setObjectName("avg")
        self.shutter = QtWidgets.QCheckBox(Dialog)
        self.shutter.setGeometry(QtCore.QRect(340, 710, 131, 31))
        self.shutter.setObjectName("shutter")
        self.acquisition_delay_display = QtWidgets.QLabel(Dialog)
        self.acquisition_delay_display.setGeometry(QtCore.QRect(30, 770, 251, 31))
        self.acquisition_delay_display.setObjectName("acquisition_delay_display")
        self.processing_delay_display = QtWidgets.QLabel(Dialog)
        self.processing_delay_display.setGeometry(QtCore.QRect(30, 820, 251, 31))
        self.processing_delay_display.setObjectName("processing_delay_display")
        self.refresh_rate_display = QtWidgets.QLabel(Dialog)
        self.refresh_rate_display.setGeometry(QtCore.QRect(30, 870, 261, 31))
        self.refresh_rate_display.setObjectName("refresh_rate_display")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_dark.setText(_translate("Dialog", "Dark Spectrum"))
        self.label_ref.setText(_translate("Dialog", "Référence"))
        self.label_intensity.setText(_translate("Dialog", "Intensité"))
        self.label_abs.setText(_translate("Dialog", "Absorbance"))
        self.refresh_dark_spectrum.setText(_translate("Dialog", "refresh"))
        self.refresh_ref.setText(_translate("Dialog", "refresh"))
        self.label_tint.setText(_translate("Dialog", "T int"))
        self.label_avg.setText(_translate("Dialog", "averaging"))
        self.shutter.setText(_translate("Dialog", "Shutter"))
        self.acquisition_delay_display.setText(_translate("Dialog", "durée d\'acquisition : "))
        self.processing_delay_display.setText(_translate("Dialog", "durée de calcul : "))
        self.refresh_rate_display.setText(_translate("Dialog", "période de rafraîchissement : "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
