# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/dispenser_param.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(621, 271)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(230, 220, 361, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_reagent = QtWidgets.QLabel(Dialog)
        self.label_reagent.setGeometry(QtCore.QRect(30, 70, 171, 51))
        self.label_reagent.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_reagent.setObjectName("label_reagent")
        self.label_concentration = QtWidgets.QLabel(Dialog)
        self.label_concentration.setGeometry(QtCore.QRect(30, 150, 171, 51))
        self.label_concentration.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_concentration.setObjectName("label_concentration")
        self.reagentC = QtWidgets.QTextEdit(Dialog)
        self.reagentC.setGeometry(QtCore.QRect(490, 70, 101, 51))
        self.reagentC.setObjectName("reagentC")
        self.reagentB = QtWidgets.QTextEdit(Dialog)
        self.reagentB.setGeometry(QtCore.QRect(360, 70, 101, 51))
        self.reagentB.setObjectName("reagentB")
        self.reagentA = QtWidgets.QTextEdit(Dialog)
        self.reagentA.setGeometry(QtCore.QRect(230, 70, 101, 51))
        self.reagentA.setObjectName("reagentA")
        #self.reagentA.toPlainText
        self.Ca = QtWidgets.QDoubleSpinBox(Dialog)
        self.Ca.setGeometry(QtCore.QRect(230, 150, 101, 51))
        self.Ca.setDecimals(6)
        self.Ca.setSingleStep(1e-06)
        self.Ca.setObjectName("Ca")
        #self.Ca.setValue
        self.Cb = QtWidgets.QDoubleSpinBox(Dialog)
        self.Cb.setGeometry(QtCore.QRect(360, 150, 101, 51))
        self.Cb.setDecimals(6)
        self.Cb.setSingleStep(1e-06)
        self.Cb.setObjectName("Cb")
        self.Cc = QtWidgets.QDoubleSpinBox(Dialog)
        self.Cc.setGeometry(QtCore.QRect(490, 150, 101, 51))
        self.Cc.setDecimals(6)
        self.Cc.setSingleStep(1e-06)
        self.Cc.setObjectName("Cc")
        self.syringeA = QtWidgets.QCheckBox(Dialog)
        self.syringeA.setGeometry(QtCore.QRect(230, 10, 101, 51))
        self.syringeA.setCheckable(True)
        self.syringeA.setObjectName("syringeA")
        self.syringeB = QtWidgets.QCheckBox(Dialog)
        self.syringeB.setGeometry(QtCore.QRect(360, 10, 101, 51))
        self.syringeB.setCheckable(True)
        self.syringeB.setObjectName("syringeB")
        self.syringeC = QtWidgets.QCheckBox(Dialog)
        self.syringeC.setGeometry(QtCore.QRect(490, 10, 101, 51))
        self.syringeC.setCheckable(True)
        self.syringeC.setObjectName("syringeC")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_reagent.setText(_translate("Dialog", "Reagent"))
        self.label_concentration.setText(_translate("Dialog", "Concentration (mol/L)"))
        self.reagentC.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">unknown</p></body></html>"))
        self.reagentB.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">NaOH</p></body></html>"))
        self.reagentA.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">HCl</p></body></html>"))
        self.syringeA.setText(_translate("Dialog", "Syringe A"))
        self.syringeB.setText(_translate("Dialog", "Syringe B"))
        self.syringeC.setText(_translate("Dialog", "Syringe C"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
