# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../panneau_de_controle.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget, plot
import pyqtgraph as pg
from IHM import IHM
from expConfig import ExpConfig
from calBox import CalBox
from spectrumConfig import SpectrumConfigWindow
from savingConfig import SavingConfig
from windowHandler import WindowHandler

from pHmeter import *
from spectro.absorbanceMeasure import AbsorbanceMeasure
from syringePump import *
from peristalticPump import *

from Phidget22.Devices.VoltageInput import VoltageInput
from Phidget22.Devices.DigitalInput import DigitalInput
from Phidget22.Devices.DigitalOutput import DigitalOutput
from Phidget22.Devices.Stepper import Stepper
from oceandirect.OceanDirectAPI import Spectrometer as Sp, OceanDirectAPI
from oceandirect.od_logger import od_logger


class ControlPannel(object):
    #Pour instancier la classe ControlPannel on doit avoir instancié les classes IHM et windowhandler
    def __init__(self, ihm:IHM=None, win:WindowHandler=None):
        print("initialisation du panneau de contrôle") 
        self.ihm=ihm #ihm passé de attribut 
        self.win=win
        self.phmeter=ihm.phmeter
        self.spectro_unit=ihm.spectro_unit
        self.syringe_pump=ihm.syringe_pump
        self.peristaltic_pump=ihm.peristaltic_pump


    ### Méthodes pour le pH mètre
    def link_pHmeter2IHM(self):
        if self.phmeter.state=='closed':
            self.phmeter.connect()
        if self.phmeter.state=='open':
            #affichage des données de calibration
            self.onCalibrationChange()
            #pH en direct
            self.direct_pH.display(self.phmeter.currentPH) #pH instantané
            self.phmeter.voltagechannel.setOnVoltageChangeHandler(self.displayDirectPH) #à chaque changement
            self.phmeter.activateStabilityLevel()
            self.phmeter.stab_timer.timeout.connect(self.refresh_stability_level)
            self.stab_time.valueChanged.connect(self.update_stab_time)
    
    def update_stab_time(self):
        self.phmeter.stab_time=self.stab_time.value()

    def clear_IHM(self):
        self.direct_pH.display(None) #   setDisabled()

    def displayDirectPH(self,ch,voltage): #arguments immuables
        self.phmeter.currentVoltage=voltage        
        pH = volt2pH(self.phmeter.a,self.phmeter.b,voltage)
        self.phmeter.currentPH=pH #actualisation de l'attribut de la classe pHmeter
        self.direct_pH.display(pH)
        #print("voltage change")
    
    def refresh_stability_level(self):
        self.stabilisation_level.setProperty("value", self.phmeter.stab_purcent)
        self.stability_label.setText(str(self.phmeter.stab_purcent)+"%")

    def openCalibWindow(self):
        self.window1 = QtWidgets.QDialog()
        self.ui1 = CalBox(self.ihm.phmeter, self, self.ihm)
        self.ui1.setupUi(self.window1)
        self.window1.show()
    
    def onCalibrationChange(self):
        self.calib_text = "Current calibration data:\n"+"date: "+str(self.phmeter.CALdate)+"\n"+"temperature: "+str(self.phmeter.CALtemperature)+"°C\npH buffers: "+str(self.phmeter.CALtype)+"\nRecorded voltages:\nU4="+str(self.phmeter.U1)+"V\nU7="+str(self.phmeter.U2)+"V\nU10="+str(self.phmeter.U3)+"V\ncoefficients U=a*pH+b\na="+str(self.phmeter.a)+"\nb="+str(self.phmeter.b)
        self.calText.clear()
        self.calText.appendPlainText(self.calib_text)

### Méthodes pour le spectromètre
    def OnClick_reglage_spectro(self):
        #self.spectro_unit=self.ihm.spectro_unit
        if self.spectro_unit.state=='closed':
            self.spectro_unit.connect()
        if self.spectro_unit.state=='open':
            self.link_spectro2IHM()
        self.openSpectroWindow()

    def openSpectroWindow(self):
        self.window2 = QtWidgets.QDialog()
        self.ui2 = SpectrumConfigWindow(self.spectro_unit,self.ihm)
        self.ui2.setupUi(self.window2)
        self.window2.show()
    
    def changeShutterState(self):
        #if self.spectro_unit.state=='open':
        self.spectro_unit.changeShutterState()
        self.shutter.setChecked(not(self.spectro_unit.adv.get_enable_lamp()))

    def updateSpectrum(self):
        self.intensity_direct_plot=self.Spectrum_direct.plot([0],[0],clear = True)
        self.intensity_direct_plot.setData(self.lambdas,self.spectro_unit.current_intensity_spectrum)
        if self.spectro_unit.current_absorbance_spectrum!=None:
            self.abs_direct_plot=self.Abs_direct.plot([0],[0],clear = True)
            self.abs_direct_plot.setData(self.lambdas,self.spectro_unit.current_absorbance_spectrum)
    
    def link_spectro2IHM(self):
        #mise sur timer
        self.ihm.timer3s.timeout.connect(self.updateSpectrum)            
        #état réel du shutter
        self.shutter.setChecked(not(self.spectro_unit.adv.get_enable_lamp()))
        self.shutter.clicked.connect(self.changeShutterState)
        #config de l'affichage du spectre courant
        self.lambdas=self.spectro_unit.wavelengths      
        self.abs_direct_plot=self.Abs_direct.plot([0],[0])
        self.intensity_direct_plot=self.Spectrum_direct.plot([0],[0])

#Méthodes pour l'enregistrement des données et configuration des séquences
    def openConfigWindow(self):
        self.window3 = QtWidgets.QDialog()
        self.ui3 = ExpConfig(self.ihm, self.win)
        self.ui3.setupUi(self.window3)
        self.window3.show()
    
    def openSavingConfigWindow(self):
        self.win4 = SavingConfig(self.ihm) #l'instance de IHM est passée en attribut
        self.win4.show()

### Méthodes pour le pousse-seringue
    def set_reference_position(self):
        self.syringe_pump.setReference()
        #maj levelbar
        self.base_level=self.syringe_pump.size-round(self.syringe_pump.stepper.getPosition(),0)
        self.base_level_bar.setProperty("value", self.base_level)
        self.base_level_number.setText("%d uL" % self.base_level)

    def unload_base(self): #appelée lors de l'appui sur le bouton unload base
        print(self)
        vol=self.unload_base_box.value()
        self.syringe_pump.simple_dispense(vol,ev=0)
        #maj levelbar
        self.base_level_bar.setProperty("value", self.syringe_pump.base_level_uL)
        self.base_level_number.setText("%d uL" % self.syringe_pump.base_level_uL)

    def reload_base(self): #lors de l'appui sur load_base_button
        vol=self.load_base_box.value()
        self.syringe_pump.simple_refill(vol)
        #maj levelbar
        self.base_level_bar.setProperty("value", self.syringe_pump.base_level_uL)
        self.base_level_number.setText("%d uL" % self.syringe_pump.base_level_uL)
    
    def full_reload(self):
        self.syringe_pump.full_refill()
        #maj levelbar
        self.base_level_bar.setProperty("value", self.syringe_pump.size)
        self.base_level_number.setText("%d uL"%self.syringe_pump.size)
    
    #Suppose que le pousse seringue soit ouvert
    def link_SyringePump2IHM(self):
#attention. les connexions clicked.connect de signaux avec des slots sont recréées à chaque appel.
#Il faut donc supprimer les connexions pour pas que les slots soient effectués plusieurs fois de suite

        self.base_level=self.syringe_pump.size-self.syringe_pump.stepper.getPosition()
        
        #reference
        self.make_ref_button.disconnect()
        self.make_ref_button.clicked.connect(self.set_reference_position)
        #action buttons
        self.stop_syringe.disconnect()
        self.stop_syringe.clicked.connect(self.syringe_pump.ForceStop)

        self.unload_base_button.disconnect()
        self.unload_base_button.clicked.connect(self.unload_base)

        self.reload_base_button.disconnect()
        self.reload_base_button.clicked.connect(self.reload_base)

        self.full_reload_button.disconnect()
        self.full_reload_button.clicked.connect(self.full_reload)

        self.dispense_base_button.disconnect()
        self.dispense_base_button.clicked.connect(self.dispense_base)

        self.added_acid.disconnect()
        self.added_acid.valueChanged.connect(self.actualize_counts_on_acid_value_change)

        self.reset_added_count.disconnect()
        self.reset_added_count.clicked.connect(self.reset_volume_count)

        #Display
        self.base_level_bar.setProperty("value", self.base_level)
        self.base_level_number.setText("%d uL" % self.base_level)
        self.added_base.setText("0")

    def dispense_base(self):
        vol=self.dispense_base_box.value()
        self.syringe_pump.simple_dispense(vol) #ev=1 default
        #maj levelbar
        self.base_level_bar.setProperty("value", self.syringe_pump.base_level_uL)
        self.base_level_number.setText("%d uL" % self.syringe_pump.base_level_uL)
        #maj volume count
        self.added_base.setText("%d" %self.syringe_pump.added_base_uL)
        self.added_total.setText("%d" %self.syringe_pump.added_total_uL)
    
    def reset_volume_count(self):
        self.syringe_pump.added_acid_uL=0
        self.syringe_pump.added_base_uL=0
        self.syringe_pump.added_total_uL=0
        self.syringe_pump.acid_dispense_log=[]
        self.syringe_pump.base_dispense_log=[]
        self.added_acid.setValue(0)
        self.added_base.setText("0")
        self.added_total.setText("0" )

    def actualize_counts_on_acid_value_change(self):
        #modification de acid et total dans la classe syringe_pump
        self.syringe_pump.added_acid_uL=self.added_acid.value()
        self.syringe_pump.added_total_uL=self.syringe_pump.added_acid_uL+self.syringe_pump.added_base_uL
        #modif de l'affichage total count
        self.added_total.setText("%d" %self.syringe_pump.added_total_uL)
        self.syringe_pump.acid_dispense_log = self.syringe_pump.added_acid_uL


### Méthodes pour la pompe péristaltique
    def link_pump2IHM(self):
        #print("pompe péristaltique reliée au panneau de controle")
        self.start_pump.clicked.connect(self.peristaltic_pump.start)
        self.stop_pump.clicked.connect(self.peristaltic_pump.stop)
        self.change_dir.clicked.connect(self.peristaltic_pump.change_direction)
        self.pump_speed_rpm.valueChanged.connect(self.update_pump_speed)

    def update_pump_speed(self):
        self.peristaltic_pump.setVelocity_rpm(self.pump_speed_rpm.value())

### Définition et config des widgets
    def setupUi(self, MainWindow):
        #global
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1054, 825)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        #labels   
        self.pH_label = QtWidgets.QLabel(self.centralwidget)
        self.pH_label.setGeometry(QtCore.QRect(680, 80, 51, 51))
        self.pH_label.setObjectName("pH_label")
        self.abs_label = QtWidgets.QLabel(self.centralwidget)
        self.abs_label.setGeometry(QtCore.QRect(10, 10, 421, 41))
        self.abs_label.setObjectName("abs_label")
        self.last_cal_label = QtWidgets.QLabel(self.centralwidget)
        self.last_cal_label.setGeometry(QtCore.QRect(530, 130, 191, 41))
        self.last_cal_label.setObjectName("last_cal_label")

        #Ph-mètre    
        self.connect_phmeter = QtWidgets.QPushButton(self.centralwidget)
        self.connect_phmeter.setGeometry(QtCore.QRect(540, 320, 150, 51))
        self.connect_phmeter.setObjectName("connect_phmeter")
        self.connect_phmeter.clicked.connect(self.link_pHmeter2IHM) #param de l'ihm
        self.direct_pH = QtWidgets.QLCDNumber(self.centralwidget)
        self.direct_pH.setGeometry(QtCore.QRect(730, 80, 101, 51))
        self.direct_pH.setObjectName("direct_pH")
        self.direct_pH.setNumDigits(6)
        self.stab_time = QtWidgets.QSpinBox(self.centralwidget)
        self.stab_time.setGeometry(QtCore.QRect(540, 30, 50, 30))
        self.stab_time.setMaximum(300) #300 seconds=1minute
        self.stab_time.setSingleStep(1)
        self.stab_time.setProperty("value", 10)
        self.stab_time.setObjectName("stab_time")
        self.stabilisation_level = QtWidgets.QProgressBar(self.centralwidget)
        self.stabilisation_level.setGeometry(QtCore.QRect(730, 30, 101, 31))
        self.stabilisation_level.setMaximum(100)
        self.stabilisation_level.setProperty("value", 15)
        self.stabilisation_level.setTextVisible(False)
        self.stabilisation_level.setOrientation(QtCore.Qt.Horizontal)
        self.stabilisation_level.setObjectName("stabilisation_level")
        self.stability_label = QtWidgets.QLabel(self.centralwidget)
        self.stability_label.setGeometry(QtCore.QRect(640, 30, 81, 31))
        self.stability_label.setObjectName("stability_label")
        self.calText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.calText.setGeometry(QtCore.QRect(700, 170, 300, 241))
        self.calText.setSizeIncrement(QtCore.QSize(0, 0))
        self.calText.setObjectName("calText")
        self.cal_button = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openCalibWindow())
        self.cal_button.setGeometry(QtCore.QRect(890, 50, 121, 61))
        self.cal_button.setObjectName("cal_button")

        #Spectrométrie
        #graphique
        self.graphic_tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.graphic_tabs.setGeometry(QtCore.QRect(10, 50, 511, 391))
        self.graphic_tabs.setObjectName("graphic_tabs")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("absorbance")
        self.Abs_direct = pg.PlotWidget(self.tab1)        
        self.Abs_direct.setGeometry(QtCore.QRect(0, 0, 511, 391))
        self.Abs_direct.setObjectName("Abs_direct")  
        self.graphic_tabs.addTab(self.tab1, "absorbance")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("intensity spectrum")
        self.Spectrum_direct = pg.PlotWidget(self.tab_2)
        self.Spectrum_direct.setGeometry(QtCore.QRect(0, 0, 511, 391))
        self.Spectrum_direct.setObjectName("Spectrum_direct")
        self.graphic_tabs.addTab(self.tab_2, "intensity")
        
      
        self.shutter = QtWidgets.QCheckBox(self.centralwidget) #clicked = lambda: self.changeShutterState())
        self.shutter.setGeometry(QtCore.QRect(250, 500, 111, 41))
        self.shutter.setObjectName("shutter")
        self.reglage_spectro = QtWidgets.QPushButton(self.centralwidget) #, )
        self.reglage_spectro.setGeometry(QtCore.QRect(380, 500, 140, 61))
        self.reglage_spectro.setObjectName("reglage_spectro")
        self.reglage_spectro.clicked.connect(self.OnClick_reglage_spectro)

        #Syringe Pump
        self.label_base_level = QtWidgets.QLabel(self.centralwidget)
        self.label_base_level.setGeometry(QtCore.QRect(560, 420, 301, 41))
        self.label_base_level.setAutoFillBackground(False)
        self.label_base_level.setObjectName("label_base_level")
        self.base_level_number = QtWidgets.QLabel(self.centralwidget)
        self.base_level_number.setGeometry(QtCore.QRect(550, 580, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.base_level_number.setFont(font)
        self.base_level_number.setObjectName("base_level_number")
        self.unload_base_button = QtWidgets.QPushButton(self.centralwidget)
        self.unload_base_button.setGeometry(QtCore.QRect(600, 530, 71, 41))
        self.unload_base_button.setObjectName("unload_base_button")
        self.unload_base_box = QtWidgets.QSpinBox(self.centralwidget)
        self.unload_base_box.setGeometry(QtCore.QRect(680, 530, 61, 41))
        self.unload_base_box.setObjectName("unload_base_box")
        self.unload_base_box.setRange(0,450)
        self.reload_base_button = QtWidgets.QPushButton(self.centralwidget)
        self.reload_base_button.setGeometry(QtCore.QRect(600, 470, 71, 41))
        self.reload_base_button.setObjectName("reload_base_button")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(710, 600, 311, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setObjectName("gridLayout")
        self.added_acid = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.added_acid.setObjectName("added_acid")
        self.gridLayout.addWidget(self.added_acid, 1, 2, 1, 1)
        self.added_total_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.added_total_label.setAutoFillBackground(False)
        self.added_total_label.setObjectName("added_total_label")
        self.gridLayout.addWidget(self.added_total_label, 3, 1, 1, 1)
        self.added_volume_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.added_volume_label.setAutoFillBackground(False)
        self.added_volume_label.setObjectName("added_volume_label")
        self.gridLayout.addWidget(self.added_volume_label, 0, 2, 1, 1)
        self.reset_added_count = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.reset_added_count.setObjectName("reset_added_count")
        self.gridLayout.addWidget(self.reset_added_count, 4, 2, 1, 1)
        self.added_base_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.added_base_label.setAutoFillBackground(False)
        self.added_base_label.setObjectName("added_base_label")
        self.gridLayout.addWidget(self.added_base_label, 2, 1, 1, 1)
        self.added_acid_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.added_acid_label.setAutoFillBackground(False)
        self.added_acid_label.setObjectName("added_acid_label")
        self.gridLayout.addWidget(self.added_acid_label, 1, 1, 1, 1)
        self.added_base = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.added_base.setFont(font)
        self.added_base.setObjectName("added_base")
        self.gridLayout.addWidget(self.added_base, 2, 2, 1, 1)
        self.added_total = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.added_total.setFont(font)
        self.added_total.setObjectName("added_total")
        self.gridLayout.addWidget(self.added_total, 3, 2, 1, 1)
        self.base_level_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.base_level_bar.setGeometry(QtCore.QRect(550, 470, 31, 101))
        self.base_level_bar.setMinimum(0)
        self.base_level_bar.setMaximum(400)
        self.base_level_bar.setTextVisible(True)
        self.base_level_bar.setOrientation(QtCore.Qt.Vertical)
        self.base_level_bar.setObjectName("base_level_bar")
        self.make_ref_button = QtWidgets.QPushButton(self.centralwidget)
        self.make_ref_button.setGeometry(QtCore.QRect(550, 610, 151, 41))
        self.make_ref_button.setObjectName("make_ref_button")
        self.load_base_box = QtWidgets.QSpinBox(self.centralwidget)
        self.load_base_box.setGeometry(QtCore.QRect(680, 470, 61, 41))
        self.load_base_box.setObjectName("load_base_box")
        self.load_base_box.setRange(0,450)
        self.full_reload_button = QtWidgets.QPushButton(self.centralwidget)
        self.full_reload_button.setGeometry(QtCore.QRect(750, 470, 91, 41))
        self.full_reload_button.setObjectName("full_reload_button")
        self.dispense_base_button = QtWidgets.QPushButton(self.centralwidget)
        self.dispense_base_button.setGeometry(QtCore.QRect(880, 530, 141, 41))
        self.dispense_base_button.setObjectName("dispense_base_button")
        self.dispense_base_box = QtWidgets.QSpinBox(self.centralwidget)
        self.dispense_base_box.setGeometry(QtCore.QRect(810, 530, 61, 41))
        self.dispense_base_box.setObjectName("dispense_base_box")
        self.dispense_base_box.setRange(0,450)
        self.stop_syringe = QtWidgets.QPushButton(self.centralwidget)
        self.stop_syringe.setGeometry(QtCore.QRect(910, 470, 91, 41))
        self.stop_syringe.setObjectName("stop_syringe")       
        self.connect_syringe_pump = QtWidgets.QPushButton(self.centralwidget)
        self.connect_syringe_pump.setGeometry(QtCore.QRect(550, 660, 150, 41))
        self.connect_syringe_pump.setObjectName("connect_syringe_pump") 
        self.connect_syringe_pump.clicked.connect(self.connectSyringePump)#bouton de connexion

        #Peristaltic Pump
        self.connect_pump = QtWidgets.QPushButton(self.centralwidget)
        self.connect_pump.setGeometry(QtCore.QRect(400, 570, 120, 30))
        self.connect_pump.setObjectName("connect_pump")
        #self.connect_pump.clicked.connect(self.ihm.connectPeristalticPump)
        self.connect_pump.clicked.connect(self.connectPeristalticPump)   
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(260, 560, 221, 180))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.group_peristaltic_pump = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.group_peristaltic_pump.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.group_peristaltic_pump.setContentsMargins(0, 0, 0, 0)
        self.group_peristaltic_pump.setSpacing(0)
        self.group_peristaltic_pump.setObjectName("group_peristaltic_pump")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.group_peristaltic_pump.addWidget(self.label)
        self.start_pump = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.start_pump.setObjectName("start_pump")
        self.group_peristaltic_pump.addWidget(self.start_pump)
        self.stop_pump = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.stop_pump.setObjectName("stop_pump")
        self.group_peristaltic_pump.addWidget(self.stop_pump)
        self.change_dir = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.change_dir.setObjectName("change_dir")
        self.group_peristaltic_pump.addWidget(self.change_dir)
        self.pump_speed_rpm = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.pump_speed_rpm.setAccessibleName("")
        self.pump_speed_rpm.setMaximum(1200)
        self.pump_speed_rpm.setSingleStep(10)
        self.pump_speed_rpm.setProperty("value", 60)
        self.pump_speed_rpm.setObjectName("pump_speed_rpm")
        self.group_peristaltic_pump.addWidget(self.pump_speed_rpm)

        #Tous les appareils
        self.close_all = QtWidgets.QPushButton(self.centralwidget)
        self.close_all.setGeometry(QtCore.QRect(560, 720, 101, 51))
        self.close_all.setObjectName("close_all") 
        self.close_all.clicked.connect(self.ihm.close_all_devices)
        self.close_all.clicked.connect(self.clear_IHM)

        #application
        self.titration_button = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openConfigWindow())
        self.titration_button.setGeometry(QtCore.QRect(20, 700, 171, 51))
        self.titration_button.setObjectName("titration_button")
        self.saving_config = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openSavingConfigWindow())
        self.saving_config.setGeometry(QtCore.QRect(20, 520, 171, 51))
        self.saving_config.setObjectName("saving_config")
        self.save_button = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.ihm.createDirectMeasureFile())
        self.save_button.setGeometry(QtCore.QRect(20, 610, 171, 51))
        self.save_button.setObjectName("save_button")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1054, 18))
        self.menubar.setObjectName("menubar")
        self.menuPanneau_de_controle = QtWidgets.QMenu(self.menubar)
        self.menuPanneau_de_controle.setObjectName("menuPanneau_de_controle")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuPanneau_de_controle.menuAction())
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        #pH meter
        self.connect_phmeter.setText(_translate("MainWindow", "connect pH meter"))
        self.pH_label.setText(_translate("MainWindow", "pH"))
        self.stability_label.setText(_translate("MainWindow", "stability"))
        self.stabilisation_level.setFormat(_translate("MainWindow", "%p%"))
        self.cal_button.setText(_translate("MainWindow", "calibration"))

        #spectro
        self.abs_label.setText(_translate("MainWindow", "Absorbance direct et référence"))
        self.shutter.setText(_translate("MainWindow", "shutter"))
        self.reglage_spectro.setText(_translate("MainWindow", "réglages spectro"))
        
        #pousse seringue
        self.label_base_level.setText(_translate("MainWindow", "basic syringe level (0 - 400uL)"))
        self.base_level_number.setText(_translate("MainWindow", "100 uL"))
        self.unload_base_button.setText(_translate("MainWindow", "unload"))
        self.reload_base_button.setText(_translate("MainWindow", "load"))
        self.added_total_label.setText(_translate("MainWindow", "total"))
        self.added_volume_label.setText(_translate("MainWindow", "added volume (uL)"))
        self.reset_added_count.setText(_translate("MainWindow", "Reset"))
        self.added_base_label.setText(_translate("MainWindow", "NaOH 0.1M (base)"))
        self.added_acid_label.setText(_translate("MainWindow", "HCl 0.1M (acid)"))
        self.added_base.setText(_translate("MainWindow", "55 uL"))
        self.added_total.setText(_translate("MainWindow", "0 uL"))
        self.base_level_bar.setFormat(_translate("MainWindow", "%p%"))
        self.make_ref_button.setText(_translate("MainWindow", "make reference \n"
" on full syringe"))
        self.full_reload_button.setText(_translate("MainWindow", "Full reload"))
        self.dispense_base_button.setText(_translate("MainWindow", "Dispense base (uL)"))
        self.stop_syringe.setText(_translate("MainWindow", "Stop"))
        self.connect_syringe_pump.setText(_translate("MainWindow", "connect Syringe Pump"))

        #Peristaltic Pump
        self.connect_pump.setText(_translate("MainWindow", "connect pump"))
        self.label.setText(_translate("MainWindow", "Peristaltic Pump"))
        self.start_pump.setText(_translate("MainWindow", "Start"))
        self.stop_pump.setText(_translate("MainWindow", "Stop"))
        self.change_dir.setText(_translate("MainWindow", "change Direction"))

        #application
        self.titration_button.setText(_translate("MainWindow", "lancement du titrage"))
        self.saving_config.setText(_translate("MainWindow", "Configure data saving"))
        self.save_button.setText(_translate("MainWindow", "Save current measure"))
        self.close_all.setText(_translate("MainWindow","close devices"))
        self.menuPanneau_de_controle.setTitle(_translate("MainWindow", "Panneau de contrôle"))

    def connectSyringePump(self):
        self.syringe_pump.connect()
        if self.syringe_pump.state=='open':
            self.link_SyringePump2IHM()

    def connectPeristalticPump(self):
        self.peristaltic_pump.connect()
        if self.peristaltic_pump.state=='open':
            self.link_pump2IHM()

#Idée : lancer l'interface. Gérer l'allumage et connexion de chaque appareil sur l'interface via des boutons
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    itf=IHM()
    win=WindowHandler()
    ui = ControlPannel(ihm=itf,win=win)
    ui.setupUi(MainWindow)
    MainWindow.show()        
    sys.exit(app.exec_())
        